apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {APPNAME}-test
spec:
  inputs:
    resources:
      - name: git-source-web
        type: git
      - name: docker-image-web
        type: image
    params:
      - name: testScript
        description: The path to the bash file for testing 
  steps:
  - name: modify-app-deploy-yaml
    image: registry.access.redhat.com/ubi8/ubi:latest
    workingDir: /workspace/git-source-web
    command: ["/bin/bash"]
    args:
      - -c
      - |
        APPNAME={APPNAME}
        PORT={PORT}
        DEVNS={DEVNS}
        /workspace/git-source-web/test/$(inputs.params.testScript)
