apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {APPNAME}-pipeline
spec:
  resources:
    - name: {APPNAME}-gitsrc
      type: git
    - name: {APPNAME}-image
      type: image
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: "k8s"
    - name: deploy-sandbox
      description: deploy to sandbox
      default: "{DEPLOY-SANDBOX}"
    - name: deploy-dev
      description: deploy to dev
      default: "{DEPLOY-DEV}"
    - name: deploy-test
      description: deploy to test
      default: "{DEPLOY-TEST}"
    - name: deploy-qa
      description: deploy to qa
      default: "{DEPLOY-QA}"
    - name: prod
      description: deploy to prod
      default: "{PROD}"
  tasks:
  - name: test-task
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    results:
      - name: ok
        description: indicates whether the test passed
    runAfter:
      - build-task
    taskRef:
      name: {APPNAME}-test
  - name: prod
    when:
      - input: $(params.prod)
        operator: in
        values: ["true"]
      - input: $(tasks.test-task.results.ok)
        operator: in
        values: ["yes"]
    results:
      - name: ok
        description: indicates whether the test passed
    resources:
      inputs:
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - deploy-qa
    taskRef:
      name: {APPNAME}-prod
