apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-{APPNAME}-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{APPNAME}-listener
    weight: 100
