apiVersion: apps/v1
kind: Deployment
metadata:
  name: {APPNAME}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {APPNAME}
  template:
    metadata:
      name: pod-{APPNAME}
      labels:
        app: {APPNAME}
    spec:
      containers:
        - name: {APPNAME}
          image: __IMAGE__
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 60

