apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {APPNAME}-app
  namespace:  {DEVOPSNS}
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  selector:
    matchExpressions:
      - key:  appgroup
        operator: In
        values: [ "{APPNAME}" ]            
