apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {APPNAME}-placementrule
  namespace: {DEVOPSNS}
  labels:
    appgroup: {APPNAME}
spec:
  clusterLabels:
    matchLabels:
      name: cpeir-mcm
  clusterReplicas:  1
