apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {APPNAME}-pipeline
spec:
  resources:
    - name: {APPNAME}-gitsrc
      type: git
    - name: {APPNAME}-image
      type: image
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: "k8s"
    - name: deploy-dev
      description: deploy to dev
      default: "{DEPLOY-DEV}"
    - name: deploy-qa
      description: deploy to qa
      default: "{DEPLOY-QA}"
  tasks:
  - name: build-task
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    taskRef:
      name: {APPNAME}-build
  - name: check-task
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    results:
      - name: ok
        description: indicates whether the test passed
    runAfter:
      - build-task
    taskRef:
      name: {APPNAME}-test
  - name: check-deploy-dev
    conditions:
      - conditionRef: "file-exists"
        resources:
          - name: workspace
            resource: source-repo
            from: [first-create-file]
    taskRef:
      name: echo-hello
  - name: deploy-dev
    when:
      - input: $(params.deploy-dev)
        operator: in
        values: ["true"]
      - input: $(tasks.test-task.results.ok)
        operator: in
        values: ["yes"]
    results:
      - name: ok
        description: indicates whether the test passed
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - check-task
    taskRef:
      name: {APPNAME}-deploy-sandbox
  - name: test
    when:
      - input: $(params.deploy-dev)
        operator: in
        values: ["true"]
      - input: $(tasks.deploy-dev.results.ok)
        operator: in
        values: ["yes"]
    results:
      - name: ok
        description: indicates whether the test passed
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - deploy-sandbox
    taskRef:
      name: {APPNAME}-deploy-dev
  - name: deploy-test
    when:
      - input: $(params.deploy-test)
        operator: in
        values: ["true"]
      - input: $(tasks.test-task.results.ok)
        operator: in
        values: ["yes"]
    results:
      - name: ok
        description: indicates whether the test passed
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - deploy-dev
    taskRef:
      name: {APPNAME}-deploy-test
  - name: deploy-qa
    when:
      - input: $(params.deploy-qa)
        operator: in
        values: ["true"]
      - input: $(tasks.test-task.results.ok)
        operator: in
        values: ["yes"]
    results:
      - name: ok
        description: indicates whether the test passed
    resources:
      inputs:
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - deploy-test
    taskRef:
      name: {APPNAME}-deploy-qa
  - name: prod
    when:
      - input: $(params.prod)
        operator: in
        values: ["true"]
      - input: $(tasks.test-task.results.ok)
        operator: in
        values: ["yes"]
    results:
      - name: ok
        description: indicates whether the test passed
    resources:
      inputs:
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - deploy-qa
    taskRef:
      name: {APPNAME}-prod
