apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {APPNAME}-pipeline
spec:
  resources:
    - name: {APPNAME}-gitsrc
      type: git
    - name: {APPNAME}-image
      type: image
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: "k8s"
    - name: deploy-dev
      description: deploy to dev
      default: "{DEPLOY-DEV}"
    - name: deploy-qa
      description: deploy to qa
      default: "{DEPLOY-QA}"
  tasks:
  - name: scan-task
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
    params:
      - name: SONAR_HOST_URL
        value: ""
      - name: SONAR_PROJECT_KEY
        value: ""
    taskRef:
      name: {APPNAME}-check
  - name: build-task
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - scan-task
    taskRef:
      name: {APPNAME}-build
  - name: deploy-dev
    #when: the when operator will be available in v0.16
    #  - input: $(params.deploy-dev)
    #    operator: in
    #    values: ["true"]
    #  - input: $(tasks.test-task.results.ok)
    #    operator: in
    #    values: ["yes"]
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - build-task
    taskRef:
      name: {APPNAME}-deploy-dev
  - name: test
    #when:
    #  - input: $(params.deploy-dev)
    #    operator: in
    #    values: ["true"]
    #  - input: $(tasks.deploy-dev.results.ok)
    #    operator: in
    #    values: ["yes"]
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - deploy-dev
    taskRef:
      name: {APPNAME}-test
  - name: deploy-qa
    #when:
    #  - input: $(params.deploy-qa)
    #    operator: in
    #    values: ["true"]
    #  - input: $(tasks.test-task.results.ok)
    #    operator: in
    #    values: ["yes"]
    resources:
      inputs:
        - name: {APPNAME}-gitsrc
          resource: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resource: {APPNAME}-image
    runAfter:
      - test
    taskRef:
      name: {APPNAME}-deploy-qa
