apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {APPNAME}-gitsrc
  namespace: {DEVOPSNS}
spec:
  params:
  - name: revision
    value: master
  - name: url
    value: {GITURL}
  type: git
