apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
# This requires the simple pipeline tasks from the pipeline hotel to be installed first
# and the simple pipeline, and the conditional resource
metadata:
  name: {APPNAME}-triggertemplate
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: {APPNAME}-pipelinerun-
      namespace: {APPNAME}
    spec:
      pipelineRef:
        name: {APPNAME}-pipeline
      resources:
        - name: {APPNAME}-gitsrc
          resourceRef:
            name: {APPNAME}-gitsrc
        - name: {APPNAME}-image
          resourceRef:
            name: {APPNAME}-image
      params:
        - name: pathToYamlFile
          value: "k8s"
        - name: deploy-sandbox
          default: "{DEPLOY-SANDBOX}"
        - name: deploy-dev
          default: "{DEPLOY-DEV}"
        - name: deploy-test
          default: "{DEPLOY-TEST}"
        - name: deploy-qa
          default: "{DEPLOY-QA}"
        - name: prod
          default: "{PROD}"        
      serviceAccountName: pipeline
      timeout: "1h0m0s"
